/**
 * Seed businesses for V1 when Supabase has no data
 * @see docs/REFERENCE.md schema
 */

import type { Business } from "@/src/types";

export const SEED_BUSINESSES: Business[] = [
  {
    id: "seed-1",
    owner_id: null,
    name: "Barracuda Restaurant",
    slug: "barracuda-restaurant",
    industry: "dining",
    description: "Mediterranean fine dining with harbour views",
    address: "194 Tower Road, Sliema",
    locality: "Sliema",
    lat: 35.9125,
    lng: 14.5019,
    emoji: "🍽️",
    cover_image_url: null,
    gallery_urls: [],
    price_tier: "€€€",
    avg_price: "€45/pp",
    currency_usd: null,
    pjazza_rating: 4.7,
    pjazza_review_count: 23,
    google_rating: 4.6,
    google_review_count: 412,
    tripadvisor_rating: 4.5,
    tripadvisor_review_count: 289,
    verified: true,
    verified_at: null,
    tags: ["Harbour View", "Fine Dining"],
    vibe: { music: "Jazz", dress: "Smart casual" },
    crowd_pct: 72,
    crowd_updated_at: null,
    halal_score: null,
    dietary_tags: [],
    wheelchair_accessible: false,
    subscription: "starter",
    stripe_account_id: null,
    is_live: true,
    live_viewer_count: 24,
    stream_room_id: null,
    streaming_streak: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-2",
    owner_id: null,
    name: "Pastizzi Corner",
    slug: "pastizzi-corner",
    industry: "dining",
    description: "Traditional Maltese pastizzi & street food",
    address: "St Anne Street, Valletta",
    locality: "Valletta",
    lat: 35.8997,
    lng: 14.5147,
    emoji: "🥐",
    cover_image_url: null,
    gallery_urls: [],
    price_tier: "€",
    avg_price: "€2/piece",
    currency_usd: null,
    pjazza_rating: 4.9,
    pjazza_review_count: 156,
    google_rating: 4.8,
    google_review_count: 892,
    tripadvisor_rating: null,
    tripadvisor_review_count: null,
    verified: true,
    verified_at: null,
    tags: ["Street Food", "Local Favourite"],
    vibe: {},
    crowd_pct: 45,
    crowd_updated_at: null,
    halal_score: null,
    dietary_tags: ["vegetarian"],
    wheelchair_accessible: false,
    subscription: "free",
    stripe_account_id: null,
    is_live: true,
    live_viewer_count: 8,
    stream_room_id: null,
    streaming_streak: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-3",
    owner_id: null,
    name: "Blue Lagoon Boat Tours",
    slug: "blue-lagoon-boat-tours",
    industry: "tours",
    description: "Day trips to Comino & Blue Lagoon",
    address: "Bugibba Jetty, St Paul's Bay",
    locality: "St Paul's Bay",
    lat: 35.9487,
    lng: 14.4044,
    emoji: "⛵",
    cover_image_url: null,
    gallery_urls: [],
    price_tier: "€€",
    avg_price: "€25/person",
    currency_usd: null,
    pjazza_rating: 4.8,
    pjazza_review_count: 89,
    google_rating: 4.7,
    google_review_count: 523,
    tripadvisor_rating: 4.9,
    tripadvisor_review_count: 1204,
    verified: true,
    verified_at: null,
    tags: ["Boat", "Swimming", "Family"],
    vibe: {},
    crowd_pct: 88,
    crowd_updated_at: null,
    halal_score: null,
    dietary_tags: [],
    wheelchair_accessible: false,
    subscription: "starter",
    stripe_account_id: null,
    is_live: true,
    live_viewer_count: 15,
    stream_room_id: null,
    streaming_streak: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-4",
    owner_id: null,
    name: "Sliema Harbour Apartments",
    slug: "sliema-harbour-apartments",
    industry: "realestate",
    description: "Modern apartments with sea views",
    address: "Tower Road, Sliema",
    locality: "Sliema",
    lat: 35.9097,
    lng: 14.4998,
    emoji: "🏠",
    cover_image_url: null,
    gallery_urls: [],
    price_tier: "€€€",
    avg_price: "€1,350/mo",
    currency_usd: null,
    pjazza_rating: 4.5,
    pjazza_review_count: 12,
    google_rating: null,
    google_review_count: null,
    tripadvisor_rating: null,
    tripadvisor_review_count: null,
    verified: false,
    verified_at: null,
    tags: ["Sea View", "Long-term"],
    vibe: {},
    crowd_pct: 22,
    crowd_updated_at: null,
    halal_score: null,
    dietary_tags: [],
    wheelchair_accessible: true,
    subscription: "free",
    stripe_account_id: null,
    is_live: false,
    live_viewer_count: 0,
    stream_room_id: null,
    streaming_streak: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-5",
    owner_id: null,
    name: "Casa Rocca Piccola",
    slug: "casa-rocca-piccola",
    industry: "tours",
    description: "Historic noble house tours in Valletta",
    address: "74 Republic Street, Valletta",
    locality: "Valletta",
    lat: 35.8986,
    lng: 14.5144,
    emoji: "🏛️",
    cover_image_url: null,
    gallery_urls: [],
    price_tier: "€€",
    avg_price: "€12/person",
    currency_usd: null,
    pjazza_rating: 4.9,
    pjazza_review_count: 34,
    google_rating: 4.8,
    google_review_count: 1567,
    tripadvisor_rating: 4.9,
    tripadvisor_review_count: 892,
    verified: true,
    verified_at: null,
    tags: ["UNESCO", "History"],
    vibe: {},
    crowd_pct: 61,
    crowd_updated_at: null,
    halal_score: null,
    dietary_tags: [],
    wheelchair_accessible: false,
    subscription: "free",
    stripe_account_id: null,
    is_live: false,
    live_viewer_count: 0,
    stream_room_id: null,
    streaming_streak: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
